### ISSUE TITLE
`mapping` must be created by `aes()`

### ISSUE THREAD

**Issue by isteves** [mine-cetinkaya-rundel/errormoji#3]
Error: `mapping` must be created by `aes()`
Did you use %>% instead of +?

🗺  ❗️  ◀️ 🎨
⏩ 😦 ➕ 😄 ❓ 

Any better suggestions?  I feel like there must be a better pipe out there in emojiland!

**Comment by mine-cetinkaya-rundel** [comment]
Hm you're right, but I can't think of a better one either, and ⏩ is not bad actually!

How about  🐣 for created?
